/*
 * The performance budget.
 *
 * docs/ASSESSMENT.md records a run on a 96k-triangle part going from 1,469 ms
 * to 2,531 ms, names the two levers that control it, and stops there — nothing
 * measured it afterwards, so the next regression was going to be found by
 * somebody saying the tool felt slow.
 *
 * ── why the budget is not wall clock ─────────────────────────────────────
 *
 * Because wall clock cannot carry one. Six runs of the same analysis over the
 * same geometry in the same process, on an idle machine, spread 274 ms to
 * 497 ms — and two separate invocations disagreed about the *minimum* by 9%. A
 * shared CI runner is worse than that. A threshold loose enough not to fail on
 * that noise is too loose to notice a doubling, and one tight enough to notice
 * a doubling fails on Tuesdays. Either way it gets ignored, and this
 * repository has already learned what an ignored check costs: `verify:build`
 * was red for two weeks and took the browser and offline suites down with it.
 *
 * What *is* deterministic is the amount of work the analysis asks for. Rays
 * cast, BVH nodes visited, triangles tested: identical run to run, identical
 * on every machine, and directly downstream of both levers
 * (`SPHERE_SAMPLE_BUDGET` is a ray count; `CONE_RINGS_DEG` × `CONE_AZIMUTHS`
 * is 33 rays per sampled point). So those are budgeted exactly, and wall clock
 * is reported beside them as information with a deliberately absurd ceiling —
 * there to catch a synchronous network call or an accidental O(n²), not a
 * 20% regression.
 *
 * ── how a budget behaves ─────────────────────────────────────────────────
 *
 * It is a ceiling, not a snapshot. Work going *down* never fails — an
 * optimisation should not have to edit a test to land. Work going up by more
 * than `TOLERANCE` does fail, and the message says which counter moved and by
 * how much.
 *
 * The one thing that also fails is work dropping far *below* the recorded
 * figure, because a budget nobody ratchets down stops being a budget: after a
 * change that halves the ray count, the old ceiling would permit the whole
 * saving to be given back silently. So a saving asks to be recorded, and the
 * message says what to write.
 *
 * Run: node test/perf.mjs
 */

import { weldGeometry } from '../src/geometry/weld.js';
import { bvhWork, resetBvhWork } from '../src/geometry/bvh.js';
import { analyseMesh } from '../src/analysis/mesh.js';
import { runDFM } from '../src/rules/engine.js';
import { MATERIALS } from '../src/core/materials.js';
import * as S from './lib/shapes.mjs';

/* Room above the recorded figure before a rise is a regression.
 *
 * Tight, and it can afford to be: these counters are the same integers on
 * every run and every machine — the test asserts that below — so there is no
 * noise for a tolerance to absorb. It exists only so that an incidental change
 * somewhere else does not have to edit this file. At 10% it was too kind:
 * raising SPHERE_SAMPLE_BUDGET by 30% moved the ray count 8.6% and passed. */
const TOLERANCE = 1.02;

/* Below this fraction of the recorded figure, the budget wants updating. Set
   well clear of TOLERANCE so an ordinary change lands in neither band. */
const RATCHET = 0.70;

/* The wall-clock backstop, as a multiple of the figure recorded here. Loose on
   purpose: this machine's own runs vary by 1.8×, so anything under about 4×
   would be measuring the runner rather than the code. */
const CLOCK_CEILING = 8;

const RUNS = 3;

const CHECK_INPUT = {
  wallThk: 2.0, wallMin: 1.6, wallMax: 2.4, draftAngle: 3.0,
  ribThk: 0.9, ribH: 2.0, ribRadius: 0.5, bossOD: 4.0, bossWall: 1.0,
  hasUndercut: '0', material: 'abs', surfaceFinish: 'spi-a2', moldType: 'two-piece',
  fpc: { enabled: false, thickness: 0.2, cover: 0.5, anchors: 'holes' },
  runChecks: {
    wall: true, draft: true, ribs: true, undercut: true, sink: true,
    warp: true, transitions: true, flow: true, fpc: true,
  },
  mesh: null,
};

/*
 * The fixtures, and what each is here to hold still.
 *
 * Authored rather than loaded, for the same reason the STEP fixtures are: a
 * budget is only comparable if the input is bit-identical, and a file in
 * test/fixtures/ is regenerated by a script that may change.
 */
const CASES = [
  {
    /* A drafted shell, subdivided until the triangle count is realistic. This
       is the sphere-probe and draft-cone case — the passes the assessment
       named as the cost. */
    name: 'drafted shell, 24,576 triangles',
    make: () => S.subdivideSoup(S.hollowFrustum(20, 30, 3, 2), 5),
    budget: { rays: 224216, nodes: 12261148, tris: 4828586 },
    ms: 390,
  },
  {
    /* Small, and expensive anyway: 1,536 triangles cost 123k rays, because
       the sample budgets are what drives ray count rather than the mesh. It
       is also the undercut/lifter case, where rays are cast in the parting
       plane rather than along a face normal. */
    name: 'internal-ledge cup, 1,536 triangles',
    make: () => S.internalLedgeCup(),
    budget: { rays: 123424, nodes: 4731228, tris: 2867107 },
    ms: 140,
  },
];

const failures = [];
const lines = [];

function measure(kase) {
  const soup = kase.make();
  const geom = weldGeometry(soup.positions, soup.triCount);

  let best = Infinity;
  let work = null;
  for (let i = 0; i < RUNS; i++) {
    resetBvhWork();
    const t0 = performance.now();
    const mesh = analyseMesh(geom, {
      material: MATERIALS.abs, minDraft: 0.5, pullAxis: '+z',
      moldType: 'two-piece', manualWall: 2, suggestGate: false,
    });
    runDFM({ ...CHECK_INPUT, mesh });
    const ms = performance.now() - t0;
    /* The fastest run, not the mean. The question is what the machine can do
       when nothing else is happening on it; a slow run is measuring the
       scheduler. */
    if (ms < best) best = ms;
    const snapshot = { ...bvhWork };
    if (work && (work.rays !== snapshot.rays || work.nodes !== snapshot.nodes || work.tris !== snapshot.tris)) {
      failures.push(`${kase.name}: the work counters are not deterministic — ${JSON.stringify(work)} then ${JSON.stringify(snapshot)}. A budget over a number that moves is not a budget.`);
    }
    work = snapshot;
  }
  return { geom, work, ms: best };
}

for (const kase of CASES) {
  const { geom, work, ms } = measure(kase);
  lines.push(`  ${kase.name}`);
  lines.push(`    ${geom.triCount} triangles, ${ms.toFixed(0)} ms (best of ${RUNS}; recorded ${kase.ms} ms)`);

  for (const counter of ['rays', 'nodes', 'tris']) {
    const actual = work[counter];
    const recorded = kase.budget[counter];
    const ratio = actual / recorded;
    const arrow = ratio > 1 ? '+' : '';
    lines.push(`    ${counter.padEnd(6)} ${actual.toLocaleString('en-GB').padStart(12)}   ${arrow}${((ratio - 1) * 100).toFixed(1)}% against ${recorded.toLocaleString('en-GB')}`);

    if (ratio > TOLERANCE) {
      failures.push(`${kase.name}: ${counter} is ${actual.toLocaleString('en-GB')}, ${((ratio - 1) * 100).toFixed(0)}% over the ${recorded.toLocaleString('en-GB')} budgeted. If the extra work is wanted, raise the figure in test/perf.mjs and say in the commit message what it bought.`);
    } else if (ratio < RATCHET) {
      failures.push(`${kase.name}: ${counter} is ${actual.toLocaleString('en-GB')}, well under the ${recorded.toLocaleString('en-GB')} budgeted. Record the saving — set the budget to ${actual} — or the next change is free to give it back unnoticed.`);
    }
  }

  if (ms > kase.ms * CLOCK_CEILING) {
    failures.push(`${kase.name}: ${ms.toFixed(0)} ms against ${kase.ms} ms recorded, past the ${CLOCK_CEILING}× backstop. This one is loose enough that a slow runner cannot trip it, so something is genuinely wrong — and the work counters above will say whether it is more work or slower work.`);
  }
}

console.log('');
for (const line of lines) console.log(line);
console.log('');

if (failures.length) {
  console.log(`  ${failures.length} budget failure(s)\n`);
  for (const f of failures) console.log(`  - ${f}\n`);
  process.exit(1);
}
console.log(`  ${CASES.length * 3} work budgets held\n`);
